AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for stemma-app


Parameters:
  hostedZoneId:
    Description: ""
    Type: String
    Default: "Z0371539135CFRSV7N3PQ"
  cloudFrontAlias:
    Description: ""
    Type: String
    Default: "eg.stemma.link"
  apiAlias:
    Description: ""
    Type: String
    Default: "eg-api.stemma.link"
  certificateArnUsEast1:
    Description: ""
    Type: String
    Default: "arn:aws:acm:us-east-1:537602986733:certificate/447c1e43-350a-40cf-b971-f6e8a8287982"
  certificateArnEurope:
    Description: ""
    Type: String
    Default: "arn:aws:acm:eu-central-1:537602986733:certificate/6d7733eb-fff5-4c6e-b06d-01868a79e108"
  googleAuthClientId:
    Description: ""
    Type: String
    Default: "584519661541-m7jkpf0o4cu08jpiq4eo4bmaoa6ah7j1.apps.googleusercontent.com"

Resources:
  assetsDnsRecord:
    DependsOn: WebAppCDN
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${cloudFrontAlias}"
      Type: A
      HostedZoneId: !Sub "${hostedZoneId}"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2" #this hardcoded value is always the case https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        DNSName: !GetAtt WebAppCDN.DomainName
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${cloudFrontAlias}'
  WebAppCDN:
    DependsOn: HtmlAssetsBucket
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${cloudFrontAlias}"
        ViewerCertificate:
          AcmCertificateArn: !Sub "${certificateArnUsEast1}"
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.2_2021"
        PriceClass: "PriceClass_100"
        Enabled: 'true'
        HttpVersion: "http2"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: HtmlAssetsBucket
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" #managed Managed-CachingOptimized cache policy
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt HtmlAssetsBucket.RegionalDomainName
            Id: "HtmlAssetsBucket"
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - /
                - - origin-access-identity
                  - cloudfront
                  - !Ref CloudFrontOriginAccessIdentity
  HtmlAssetsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  HtmlAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref HtmlAssetsBucket
                - /*
      Bucket: !Ref HtmlAssetsBucket
  AccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          OAuth2Authorizer:
            JwtConfiguration:
              issuer: "https://accounts.google.com"
              audience:
                - !Sub "${googleAuthClientId}"
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        MaxAge: 600
      Domain:
        DomainName: !Sub "${apiAlias}"
        CertificateArn: !Sub "${certificateArnEurope}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Sub "${hostedZoneId}"
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: '{
        $context.requestId ; $context.authorizer.error ; $context.error.message ; $context.integration.error ; $context.integrationErrorMessage ; $context.integration.integrationStatus
        "requestId":"$context.requestId", 
        "ip": "$context.identity.sourceIp",
         "caller":"$context.identity.caller",
          "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength" 
          }'
      StageName: dev
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /hello
            Method: get

Outputs:
  HtmlAssetsBucketRegionalName:
    Description: "Name of the bucket where html assets are stored"
    Value: !Ref HtmlAssetsBucket
  CloudFormationId:
    Description: "Cloudformation id"
    Value: !GetAtt WebAppCDN.Id