AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for stemma-app


Globals:
  Function:
    Runtime: java11
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        JDBC_URL: "{{resolve:secretsmanager:prod/jdbc:SecretString:JDBC_URL}}"
        JDBC_USER: "{{resolve:secretsmanager:prod/jdbc:SecretString:JDBC_USER}}"
        JDBC_PASSWORD: "{{resolve:secretsmanager:prod/jdbc:SecretString:JDBC_PASSWORD}}"
        INVITE_SECRET: "{{resolve:secretsmanager:prod/invite:SecretString:INVITE_SECRET}}"
    Layers:
      - !Ref MyLayer


Parameters:
  hostedZoneId:
    Description: ""
    Type: String
    Default: "Z0371539135CFRSV7N3PQ"
  cloudFrontAlias:
    Description: ""
    Type: String
    Default: "web.stemma.link"
  apiAlias:
    Description: ""
    Type: String
    Default: "api.stemma.link"
  certificateArnUsEast1:
    Description: ""
    Type: String
    Default: "arn:aws:acm:us-east-1:537602986733:certificate/447c1e43-350a-40cf-b971-f6e8a8287982"
  certificateArnEurope:
    Description: ""
    Type: String
    Default: "arn:aws:acm:eu-central-1:537602986733:certificate/6d7733eb-fff5-4c6e-b06d-01868a79e108"
  googleAuthClientId:
    Description: ""
    Type: String
    Default: "584519661541-m7jkpf0o4cu08jpiq4eo4bmaoa6ah7j1.apps.googleusercontent.com"

Resources:
  assetsDnsRecord:
    DependsOn: WebAppCDN
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${cloudFrontAlias}"
      Type: A
      HostedZoneId: !Sub "${hostedZoneId}"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2" #this hardcoded value is always the case https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        DNSName: !GetAtt WebAppCDN.DomainName
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${cloudFrontAlias}'
  WebAppCDN:
    DependsOn: appbucket
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${cloudFrontAlias}"
        ViewerCertificate:
          AcmCertificateArn: !Sub "${certificateArnUsEast1}"
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.2_2021"
        PriceClass: "PriceClass_100"
        Enabled: 'true'
        HttpVersion: "http2"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: appbucket
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" #managed Managed-CachingOptimized cache policy
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt appbucket.RegionalDomainName
            Id: "appbucket"
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - /
                - - origin-access-identity
                  - cloudfront
                  - !Ref CloudFrontOriginAccessIdentity
  appbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref appbucket
                - /*
      Bucket: !Ref appbucket
  #  autosetloggroupretention:
  #    Type: AWS::Serverless::Application
  #    Properties:
  #      Location:
  #        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/auto-set-log-group-retention
  #        SemanticVersion: 1.5.0
  #      Parameters:
  #       RetentionDays: 1
  AccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          OAuth2Authorizer:
            JwtConfiguration:
              issuer: "https://accounts.google.com"
              audience:
                - !Sub "${googleAuthClientId}"
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        MaxAge: 600
      Domain:
        DomainName: !Sub "${apiAlias}"
        CertificateArn: !Sub "${certificateArnEurope}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Sub "${hostedZoneId}"
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: '{
        $context.requestId ; $context.authorizer.error ; $context.error.message ; $context.integration.error ; $context.integrationErrorMessage ; $context.integration.integrationStatus
        "requestId":"$context.requestId", 
        "ip": "$context.identity.sourceIp",
         "caller":"$context.identity.caller",
          "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength" 
          }'
      StageName: dev
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - java11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  ListStemmasFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.ListStemmas::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /stemmas
            Method: get
  DeleteStemmaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.DeleteStemma::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /stemma
            Method: delete
  CreateNewStemmaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.CreateNewStemma::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /stemma
            Method: post
  StemmaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.Stemma::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /get-stemma
            Method: post
  DeletePersonFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.DeletePerson::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /person
            Method: delete
  UpdatePersonFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.UpdatePerson::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /person
            Method: put
  CreateInvitationTokenFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.CreateInvitationToken::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /create-invite
            Method: post
  BearInvitationTokenFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.BearInvitationStemma::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /invite
            Method: post
  CreateFamilyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.CreateFamily::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /family
            Method: post
  UpdateFamilyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.UpdateFamily::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /family
            Method: put
  DeleteFamilyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: io.github.salamahin.stemma.apis.serverless.aws.DeleteFamily::apply
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /family
            Method: delete

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
