CREATE TABLE IF NOT EXISTS "StemmaUsers" (
  "id" BIGSERIAL PRIMARY KEY,
  "email" VARCHAR NOT NULL UNIQUE
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_email" ON "StemmaUsers" ("email");

CREATE TABLE IF NOT EXISTS "Stemma" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "Person" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "birthDate" DATE,
  "deathDate" DATE,
  "bio" VARCHAR,
  "stemmaId" BIGINT NOT NULL,
  CONSTRAINT "FK_Person_Stemma" FOREIGN KEY ("stemmaId") REFERENCES "Stemma"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Family" (
  "id" BIGSERIAL PRIMARY KEY,
  "stemmaId" BIGINT NOT NULL,
  CONSTRAINT "FK_Family_Stemma" FOREIGN KEY ("stemmaId") REFERENCES "Stemma"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "FamilyOwner" (
  "ownerId" BIGINT NOT NULL,
  "familyId" BIGINT NOT NULL,
  CONSTRAINT "PK_FamilyOwner" PRIMARY KEY ("ownerId", "familyId"),
  CONSTRAINT "FK_FamilyOwner_User" FOREIGN KEY ("ownerId") REFERENCES "StemmaUsers"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_FamilyOwner_Family" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PersonOwner" (
  "ownerId" BIGINT NOT NULL,
  "personId" BIGINT NOT NULL,
  CONSTRAINT "PK_PersonOwner" PRIMARY KEY ("ownerId", "personId"),
  CONSTRAINT "FK_PersonOwner_User" FOREIGN KEY ("ownerId") REFERENCES "StemmaUsers"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_PersonOwner_Person" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "StemmaOwner" (
  "ownerId" BIGINT NOT NULL,
  "stemmaId" BIGINT NOT NULL,
  CONSTRAINT "PK_StemmaOwner" PRIMARY KEY ("ownerId", "stemmaId"),
  CONSTRAINT "FK_StemmaOwner_User" FOREIGN KEY ("ownerId") REFERENCES "StemmaUsers"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_StemmaOwner_Stemma" FOREIGN KEY ("stemmaId") REFERENCES "Stemma"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Spouse" (
  "personId" BIGINT NOT NULL,
  "familyId" BIGINT NOT NULL,
  CONSTRAINT "PK_Spouse" PRIMARY KEY ("personId", "familyId"),
  CONSTRAINT "FK_Spouse_Person" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_Spouse_Family" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Child" (
  "personId" BIGINT NOT NULL,
  "familyId" BIGINT NOT NULL,
  CONSTRAINT "PK_Child" PRIMARY KEY ("personId", "familyId"),
  CONSTRAINT "FK_Child_Person" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_Child_Family" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON UPDATE CASCADE ON DELETE CASCADE
);
